### ISSUE TITLE
Linux install script doesn't work

### ISSUE THREAD

**Issue by tenor-dev** [web-eid/web-eid-app#218]
The following script listed on https://web-eid.eu actuall has the "install" lines commented out:
https://web-eid.eu/scripts/download-install-web-eid.sh

It should be also be stated in the doc and handled in the script that the official token-signing packages must be removed first, otherwise installation doesn't work.

**Comment by mrts** [comment]
Thank you for noticing! Fixed now, comments have been removed from the `sudo apt install -y ./web-eid*.deb` and subsequent lines.

New versions of the Open EID packages already contain Web eID instead of token-signing. We use the [Debian's package relationship facilities](https://www.debian.org/doc/debian-policy/ch-relationships.html#packages-which-break-other-packages-breaks) (see the package control file [here](https://github.com/web-eid/web-eid-app/blob/main/debian/control#L17-L18)) to declare conflict with token-signing and assume the users are knowledgeable enough to handle the situation.

However, you are right that we should improve the instructions on the web-eid.eu page. We will de-emphasize the Web eID packages and emphazise latest official Open EID packages more, see the change [here](https://github.com/web-eid/web-eid-spring-boot-example/commit/3eec0513d8a6558725c57c6238c7412990bbc23d). Does it look good now, do you have further suggestions?

**Comment by angryziber** [comment]
Good changes, thanks!
I somehow haven't received webeid on my machine automatically as an update.

Also, Token Signing extension is available in the Chrome Web Store, but Web eID is not, so it's not clear how to use it in e.g. Brave Browser

**Comment by mrts** [comment]
Web eID is actually published in the Chrome Web Store, but it was decided not to publicly list it as the extension does not work without the companion native app. Please install it in Brave using the direct link https://chrome.google.com/webstore/detail/web-eid/ncibgoaomkmdpilpocfeponihegamlic. I'm not sure if Brave is able to pick up the native app though, please let us know if it worked. Thank you in advance!

**Comment by mrts** [comment]
> I have received the webeid on Ubuntu 22.04, but not on 20.04. Right now it's hard to say what was the reason, probably the packages were not up to date.

Right, do I understand you correctly, that now it works in 20.04 as well?

> As for the extension in Brave - yes it works and finds the native app. Maybe it should be listed with a warning that a native app is needed, so that Brave and other Chromium-based browsers could get it easily.

I discussed this with the product owner. There has been confusion and problems reported to the customer service due to manually installing the extension from the browser store, the installer cannot remove it later etc, so it is a well-considered decision. Would guidelines in https://www.id.ee/artikkel/paigalda-id-tarkvara/ for Brave (and other Chromium-based browsers) that would contain the direct link help?

**Comment by angryziber** [comment]
1. Yes, it works with 20.04
2. The docs will be definitely better than nothing :-)
